from datetime import datetime, timezone
import logging
import os
import smtplib
from email.message import EmailMessage

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from backend.database import get_connection


logger = logging.getLogger(__name__)


def send_feedback_email(
    student_id: str | None,
    rating: int,
    category: str,
    message: str,
    email: str | None,
    created_at: str,
    feedback_id: int,
):
    """Send a feedback notification to the configured Gmail address.

    Email failure is logged but does not cancel a successfully saved feedback
    submission. This prevents a temporary Gmail/SMTP problem from losing feedback.
    """
    smtp_email = os.getenv("SMTP_EMAIL")
    smtp_app_password = os.getenv("SMTP_APP_PASSWORD")
    feedback_receiver = os.getenv("FEEDBACK_RECEIVER")

    if not smtp_email or not smtp_app_password or not feedback_receiver:
        logger.warning(
            "Gmail notification skipped: SMTP_EMAIL, SMTP_APP_PASSWORD, "
            "or FEEDBACK_RECEIVER is not configured."
        )
        return False

    # Remove normal and hidden whitespace from the Gmail App Password.
    smtp_app_password = "".join(
    character for character in smtp_app_password
    if not character.isspace()
)

    stars = "⭐" * rating
    subject = f"New AcadAI Feedback - {rating}/5"

    body = f"""New feedback has been submitted on AcadAI.

Feedback ID: {feedback_id}
Student ID: {student_id or "Not provided"}
Rating: {rating}/5 {stars}
Category: {category}

Message:
{message}

Student Email: {email or "Not provided"}
Submitted At (UTC): {created_at}
"""

    msg = EmailMessage()
    msg["From"] = smtp_email
    msg["To"] = feedback_receiver
    msg["Subject"] = subject
    msg.set_content(body)

    try:
        with smtplib.SMTP("smtp.gmail.com", 587, timeout=30) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(smtp_email, smtp_app_password)
            server.send_message(msg)

        logger.info("Feedback email sent successfully for feedback ID %s", feedback_id)
        return True

    except Exception:
        logger.exception(
            "Unable to send Gmail notification for feedback ID %s",
            feedback_id,
        )
        return False


router = APIRouter(
    prefix="/feedback",
    tags=["Feedback"]
)


# ============================================================
# REQUEST MODEL
# ============================================================

class FeedbackRequest(BaseModel):
    student_id: str | None = None
    rating: int = Field(..., ge=1, le=5)
    category: str = Field(..., min_length=1, max_length=100)
    message: str = Field(..., min_length=10, max_length=2000)
    email: str | None = Field(default=None, max_length=255)


# ============================================================
# CREATE FEEDBACK TABLE
# ============================================================

def initialize_feedback_table():
    connection = get_connection()
    cursor = connection.cursor()

    try:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS feedback (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                student_id TEXT,

                rating INTEGER NOT NULL
                    CHECK (rating >= 1 AND rating <= 5),

                category TEXT NOT NULL,

                message TEXT NOT NULL,

                email TEXT,

                created_at TEXT NOT NULL,

                FOREIGN KEY(student_id)
                    REFERENCES users(student_id)
                    ON DELETE SET NULL
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS
            idx_feedback_student
            ON feedback(student_id)
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS
            idx_feedback_created_at
            ON feedback(created_at)
        """)

        connection.commit()

    except Exception:
        connection.rollback()
        raise

    finally:
        connection.close()


# ============================================================
# SUBMIT FEEDBACK
# ============================================================

@router.post("")
def submit_feedback(feedback: FeedbackRequest):

    student_id = (
        feedback.student_id.strip().upper()
        if feedback.student_id
        else None
    )

    email = (
        feedback.email.strip()
        if feedback.email
        else None
    )

    connection = get_connection()
    cursor = connection.cursor()

    try:
        # If a student ID is supplied, verify that it exists.
        if student_id:
            cursor.execute(
                """
                SELECT student_id
                FROM users
                WHERE student_id = ?
                """,
                (student_id,)
            )

            user = cursor.fetchone()

            if not user:
                raise HTTPException(
                    status_code=404,
                    detail="Student not found"
                )

        created_at = datetime.now(
            timezone.utc
        ).isoformat()

        cursor.execute(
            """
            INSERT INTO feedback (
                student_id,
                rating,
                category,
                message,
                email,
                created_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            RETURNING id
            """,
            (
                student_id,
                feedback.rating,
                feedback.category.strip(),
                feedback.message.strip(),
                email,
                created_at
            )
        )

        result = cursor.fetchone()
        connection.commit()

        feedback_id = result["id"]

        # Send the notification only after the database commit succeeds.
        email_sent = send_feedback_email(
            student_id=student_id,
            rating=feedback.rating,
            category=feedback.category.strip(),
            message=feedback.message.strip(),
            email=email,
            created_at=created_at,
            feedback_id=feedback_id,
        )

        return {
            "success": True,
            "message": "Feedback submitted successfully.",
            "feedback_id": feedback_id,
            "email_notification_sent": email_sent,
        }

    except HTTPException:
        connection.rollback()
        raise

    except Exception as error:
        connection.rollback()

        raise HTTPException(
            status_code=500,
            detail=f"Unable to submit feedback: {error}"
        )

    finally:
        connection.close()


# ============================================================
# GET FEEDBACK FOR A STUDENT
# ============================================================

@router.get("/{student_id}")
def get_student_feedback(student_id: str):

    student_id = student_id.strip().upper()

    connection = get_connection()
    cursor = connection.cursor()

    try:
        cursor.execute(
            """
            SELECT
                id,
                student_id,
                rating,
                category,
                message,
                email,
                created_at
            FROM feedback
            WHERE student_id = ?
            ORDER BY created_at DESC
            """,
            (student_id,)
        )

        feedback = cursor.fetchall()

        return {
            "success": True,
            "feedback": feedback
        }

    finally:
        connection.close()
