import os
from datetime import datetime, timezone

from fastapi import APIRouter, Header, HTTPException
from pydantic import BaseModel, Field

from backend.database import get_connection


router = APIRouter(
    prefix="/notifications",
    tags=["Notifications"]
)


class NotificationRequest(BaseModel):
    student_id: str = Field(..., min_length=3, max_length=100)
    title: str = Field(..., min_length=1, max_length=150)
    message: str = Field(..., min_length=1, max_length=2000)
    notification_type: str = Field(
        default="announcement",
        max_length=50
    )


class BroadcastNotificationRequest(BaseModel):
    title: str = Field(..., min_length=1, max_length=150)
    message: str = Field(..., min_length=1, max_length=2000)
    notification_type: str = Field(
        default="announcement",
        max_length=50
    )


def verify_admin(admin_key: str | None):
    expected_key = os.getenv("ADMIN_NOTIFICATION_KEY")

    if not expected_key:
        raise HTTPException(
            status_code=500,
            detail="ADMIN_NOTIFICATION_KEY is not configured on the server."
        )

    if not admin_key or admin_key != expected_key:
        raise HTTPException(
            status_code=401,
            detail="Invalid admin key."
        )


def initialize_notifications_table():
    connection = get_connection()
    cursor = connection.cursor()

    try:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS notifications (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                student_id TEXT NOT NULL,
                title TEXT NOT NULL,
                message TEXT NOT NULL,
                notification_type TEXT NOT NULL DEFAULT 'announcement',
                is_read BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TEXT NOT NULL,

                FOREIGN KEY(student_id)
                    REFERENCES users(student_id)
                    ON DELETE CASCADE
            )
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_notifications_student
            ON notifications(student_id)
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_notifications_created
            ON notifications(created_at)
        """)

        connection.commit()

    except Exception:
        connection.rollback()
        raise

    finally:
        connection.close()


@router.post("/send")
def send_notification(
    notification: NotificationRequest,
    x_admin_key: str | None = Header(default=None)
):
    """
    Send a notification to one student.
    """

    verify_admin(x_admin_key)

    student_id = notification.student_id.strip().upper()

    connection = get_connection()
    cursor = connection.cursor()

    try:
        cursor.execute(
            """
            SELECT student_id
            FROM users
            WHERE student_id = ?
            """,
            (student_id,)
        )

        student = cursor.fetchone()

        if not student:
            raise HTTPException(
                status_code=404,
                detail=f"Student {student_id} not found."
            )

        created_at = datetime.now(timezone.utc).isoformat()

        cursor.execute(
            """
            INSERT INTO notifications (
                student_id,
                title,
                message,
                notification_type,
                is_read,
                created_at
            )
            VALUES (?, ?, ?, ?, FALSE, ?)
            RETURNING id
            """,
            (
                student_id,
                notification.title.strip(),
                notification.message.strip(),
                notification.notification_type.strip(),
                created_at
            )
        )

        result = cursor.fetchone()

        connection.commit()

        return {
            "success": True,
            "message": "Notification sent successfully.",
            "notification_id": result["id"],
            "student_id": student_id
        }

    except HTTPException:
        connection.rollback()
        raise

    except Exception as error:
        connection.rollback()

        raise HTTPException(
            status_code=500,
            detail=f"Unable to send notification: {error}"
        )

    finally:
        connection.close()


@router.post("/broadcast")
def broadcast_notification(
    notification: BroadcastNotificationRequest,
    x_admin_key: str | None = Header(default=None)
):
    """
    Send the same notification to every student.
    """

    verify_admin(x_admin_key)

    connection = get_connection()
    cursor = connection.cursor()

    try:
        cursor.execute(
            """
            SELECT student_id
            FROM users
            """
        )

        students = cursor.fetchall()

        if not students:
            raise HTTPException(
                status_code=404,
                detail="No students found."
            )

        created_at = datetime.now(timezone.utc).isoformat()

        count = 0

        for student in students:
            cursor.execute(
                """
                INSERT INTO notifications (
                    student_id,
                    title,
                    message,
                    notification_type,
                    is_read,
                    created_at
                )
                VALUES (?, ?, ?, ?, FALSE, ?)
                """,
                (
                    student["student_id"],
                    notification.title.strip(),
                    notification.message.strip(),
                    notification.notification_type.strip(),
                    created_at
                )
            )

            count += 1

        connection.commit()

        return {
            "success": True,
            "message": "Broadcast notification sent successfully.",
            "students_notified": count
        }

    except HTTPException:
        connection.rollback()
        raise

    except Exception as error:
        connection.rollback()

        raise HTTPException(
            status_code=500,
            detail=f"Unable to broadcast notification: {error}"
        )

    finally:
        connection.close()


@router.get("/{student_id}")
def get_notifications(student_id: str):
    """
    Get notifications for a student.
    """

    student_id = student_id.strip().upper()

    connection = get_connection()
    cursor = connection.cursor()

    try:
        cursor.execute(
            """
            SELECT
                id,
                student_id,
                title,
                message,
                notification_type,
                is_read,
                created_at
            FROM notifications
            WHERE student_id = ?
            ORDER BY created_at DESC
            """,
            (student_id,)
        )

        notifications = cursor.fetchall()

        return {
            "success": True,
            "notifications": notifications
        }

    finally:
        connection.close()


@router.patch("/{notification_id}/read")
def mark_notification_read(
    notification_id: int,
    student_id: str
):
    """
    Mark a notification as read.
    """

    student_id = student_id.strip().upper()

    connection = get_connection()
    cursor = connection.cursor()

    try:
        cursor.execute(
            """
            UPDATE notifications
            SET is_read = TRUE
            WHERE id = ?
              AND student_id = ?
            """,
            (notification_id, student_id)
        )

        connection.commit()

        return {
            "success": True,
            "message": "Notification marked as read."
        }

    except Exception as error:
        connection.rollback()

        raise HTTPException(
            status_code=500,
            detail=f"Unable to update notification: {error}"
        )

    finally:
        connection.close()