import os
import psycopg
from psycopg.rows import dict_row


# ============================================================
# DATABASE CONFIGURATION
# ============================================================

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL environment variable is not set."
    )


# ============================================================
# COMPATIBILITY CURSOR
#
# Existing project files use SQLite-style ? placeholders.
# PostgreSQL uses %s.
#
# This wrapper lets the existing routes continue working
# without changing every SQL query.
# ============================================================

class CompatibleCursor:

    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, query, params=None):
        query = query.replace("?", "%s")

        if params is None:
            return self._cursor.execute(query)

        return self._cursor.execute(
            query,
            params
        )

    def executemany(self, query, params_seq):
        query = query.replace("?", "%s")

        return self._cursor.executemany(
            query,
            params_seq
        )

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def fetchmany(self, size=None):
        if size is None:
            return self._cursor.fetchmany()

        return self._cursor.fetchmany(size)

    def __getattr__(self, name):
        return getattr(self._cursor, name)


# ============================================================
# COMPATIBILITY CONNECTION
# ============================================================

class CompatibleConnection:

    def __init__(self, connection):
        self._connection = connection

    def cursor(self):
        return CompatibleCursor(
            self._connection.cursor()
        )

    def execute(self, query, params=None):
        query = query.replace("?", "%s")

        if params is None:
            return self._connection.execute(query)

        return self._connection.execute(
            query,
            params
        )

    def commit(self):
        return self._connection.commit()

    def rollback(self):
        return self._connection.rollback()

    def close(self):
        return self._connection.close()

    def __getattr__(self, name):
        return getattr(self._connection, name)


# ============================================================
# DATABASE CONNECTION
# ============================================================

def get_connection():

    connection = psycopg.connect(
        DATABASE_URL,
        row_factory=dict_row
    )

    return CompatibleConnection(connection)


# ============================================================
# DATABASE INITIALIZATION
# ============================================================

def initialize_database():

    connection = get_connection()
    cursor = connection.cursor()

    try:

        # ====================================================
        # USERS
        # ====================================================

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS users (

                id INTEGER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                student_id TEXT UNIQUE NOT NULL,

                full_name TEXT NOT NULL,

                email TEXT UNIQUE NOT NULL,

                password_hash TEXT NOT NULL,

                created_at TEXT NOT NULL,

                profile_picture TEXT

            )
        """)


        # ====================================================
        # ACADEMIC PROFILE
        # ====================================================

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS academic_profiles (

                id INTEGER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                student_id TEXT UNIQUE NOT NULL,

                cgpa DOUBLE PRECISION
                    NOT NULL DEFAULT 0,

                target_cgpa DOUBLE PRECISION
                    NOT NULL DEFAULT 0,

                career_goal TEXT,

                current_semester INTEGER,

                academic_year TEXT,

                updated_at TEXT NOT NULL,

                FOREIGN KEY(student_id)
                    REFERENCES users(student_id)
                    ON DELETE CASCADE

            )
        """)


        # ====================================================
        # SUBJECT RECORDS
        # ====================================================

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS academic_subjects (

                id INTEGER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                student_id TEXT NOT NULL,

                semester INTEGER
                    NOT NULL DEFAULT 1,

                academic_year TEXT
                    NOT NULL DEFAULT '2025-2026',

                course_code TEXT NOT NULL,

                course_name TEXT NOT NULL,

                marks DOUBLE PRECISION
                    NOT NULL DEFAULT 0,

                attendance_percent DOUBLE PRECISION
                    NOT NULL DEFAULT 0,

                status TEXT
                    NOT NULL DEFAULT 'completed',

                FOREIGN KEY(student_id)
                    REFERENCES users(student_id)
                    ON DELETE CASCADE

            )
        """)


        # ====================================================
        # SEMESTER INFORMATION
        # ====================================================

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS academic_semesters (

                id INTEGER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,

                student_id TEXT NOT NULL,

                semester INTEGER NOT NULL,

                academic_year TEXT NOT NULL,

                semester_cgpa DOUBLE PRECISION,

                updated_at TEXT NOT NULL,

                UNIQUE(
                    student_id,
                    semester,
                    academic_year
                ),

                FOREIGN KEY(student_id)
                    REFERENCES users(student_id)
                    ON DELETE CASCADE

            )
        """)


        # ====================================================
        # INDEXES
        # ====================================================

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS
            idx_academic_subjects_student_semester

            ON academic_subjects(
                student_id,
                semester,
                academic_year
            )
        """)


        cursor.execute("""
            CREATE INDEX IF NOT EXISTS
            idx_academic_semesters_student

            ON academic_semesters(
                student_id,
                semester,
                academic_year
            )
        """)


        # ====================================================
        # COMMIT
        # ====================================================

        connection.commit()

        print(
            "PostgreSQL database initialized successfully."
        )

    except Exception:

        connection.rollback()

        raise

    finally:

        connection.close()